### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by tbeu**
See https://github.com/vlajos/misspell_fixer

### CODE REVIEW

**Comment by casella** [comment]
I am sorry, but currently the library is hosted on SourceForge under SVN, the GitHub repo is just a mirror. I'll eventually migrate to GitHub, but I guess it will be this fall. If you can send me patches that I can apply to my SVN working copy, that would be good.

Thanks

Francesco

**Comment by dietmarw** [comment]
@casella GitHub is again your friend. Simply append `.diff` to the pull request address and you get the unified diff file which you can use for patching. I.e.,:
https://github.com/modelica-3rdparty/ThermoPower/pull/2.diff :-)

**Comment by tbeu** [comment]
@casella Did @dietmarw's guidance work for you?

**Comment by casella** [comment]
Sorry, I haven't had time to do it yet...

		Francesco


Il 13/03/2015 10:05, tbeu ha scritto:
> @casella <https://github.com/casella> Did @dietmarw
> <https://github.com/dietmarw>'s guidance work for you?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/modelica-3rdparty/ThermoPower/pull/2#issuecomment-78877798>.
>

-- 
Francesco Casella - Ph.D.
Dipartimento di Elettronica, Informazione e Bioingegneria
Politecnico di Milano
Via Ponzio 34/5
I-20133 MILANO - ITALY

Tel:    +39-02-2399-3465 (Leonardo)
         +39-02-2399-7749 (Polo di Cremona)
Fax:    +39-02-2399-3412
e-mail: francesco.casella@polimi.it
web:    http://home.dei.polimi.it/casella
Skype:  callto://francesco.casella

**Comment by tbeu** [comment]
In case you want to sync SF and github repos: http://sourceforge.net/blog/tutorial-how-to-sync-a-github-or-google-code-repo-to-a-sourceforge-project/

**Comment by dietmarw** [comment]
I don't but thanks.

**Comment by dietmarw** [comment]
The reason is simple, I don't want to encourage people to stay with SVN basically and at the same time create more work for me.

**Comment by tbeu** [comment]
> I'll eventually migrate to GitHub, but I guess it will be this fall.

Does this still hold?

**Comment by casella** [comment]
Yes, but there are (many) others higher-priority tasks in the queue, I'm 
afraid :)

		Francesco


Il 05/10/2015 22:36, tbeu ha scritto:
>     I'll eventually migrate to GitHub, but I guess it will be this fall.
>
> Does this still hold?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/modelica-3rdparty/ThermoPower/pull/2#issuecomment-145660824>.
>

-- 
Francesco Casella - Ph.D.
Dipartimento di Elettronica, Informazione e Bioingegneria
Politecnico di Milano
Via Ponzio 34/5
I-20133 MILANO - ITALY

Tel:    +39-02-2399-3465 (Leonardo)
         +39-02-2399-7749 (Polo di Cremona)
Fax:    +39-02-2399-3412
e-mail: francesco.casella@polimi.it
web:    http://home.dei.polimi.it/casella
Skype:  callto://francesco.casella

**Comment by tbeu** [comment]
OK, simply let me know when you find the time for this. I'll close it for now.

**Comment by tbeu** [comment]
> I'll eventually migrate to GitHub, but I guess it will be this fall.

As more and more Modelica libraries are hosted (not just mirrored) on GitHub, do you think, ThermoPower will migrate one day?

**Pull request closed without merging**
